name: task_manager
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  dio: ^5.8.0+1
  freezed_annotation: ^2.4.4
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Bloc & Testing
  bloc_test: ^10.0.0
  mockito: ^5.4.5

  # Code Generation
  freezed: ^2.5.8
  build_runner: ^2.4.15

  # Linting
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
